### ISSUE TITLE
Can you make support for aarch64 My android version is 6.0

### ISSUE THREAD

**Issue by XrazorXGaming** [MoeMod/CSMoE#193]
Your apk doesn't work on my phone
It says error parsing the package

**Comment by Adnan1091** [comment]
Latest nighty builds support ARM64 sign the apk with mixplorer

**Comment by XrazorXGaming** [comment]
Uhh nighty builds?

**Comment by HowToDoThis** [comment]
> 
> 
> Your apk doesn't work on my phone
> It says error parsing the package

error parsing the package does not means apk not supporting your specific platform, mostly because you had corrupted parts on apk or something else. Since our test platform are very limited, so welcome to feedback your CPU arch and benchmarks results to us for confirming more and more supported platform.

**Comment by XrazorXGaming** [comment]
Time T run some bench markings I'll just send it here when I'm done

**Comment by XrazorXGaming** [comment]
Here it is the specs

CPU | MediaTek MT6753 SoC, Cortex-A53,Mali T720 64-bit Octa Core

**Comment by HowToDoThis** [comment]
Bingo, right now having tons of CPU architectures but everyone was differ a bit. That's why we need more user feedbacking more details, for make sure that CPU Arch are supported and well performing. BTW aarch64 not supporting right now (maybe), maybe there is gonna fixed on somedays since we don't have any related devices to test it out.

**Comment by XrazorXGaming** [comment]
thx for the reply

**Comment by MoeMod** [comment]
won't fix. Android 9.0 required.
