### ISSUE TITLE
v15 bug

### ISSUE THREAD

**Issue by hzd007** [MoeMod/CSMoE#25]
Feedback bug:
The biochemical model is better optimized than the previous version, and humans can resist zombies for a while, but it is still difficult to sustain because:
Some bots shoot with a pistol. Once the BOT has no bullets, you're faced with a group of zombies. When you're chased by a group of zombies, you don't have a chance to buy bullets.
The solutions are:
1, increase the firearm backup bomb;
2. Reduce the blood volume of zombies.
3, increase weapons damage or add new weapons or enhance the fight back.
-- -- -- -- -- -- --
Cataclysm bug:
1, kill a disaster zombie 50 gold coins, only enough to buy bullets;
2. Regeneration point problem, the official CS map is no problem, but the csol catastrophe map birthplace overlap, or NPC appears in the map wall can not enter, or retreat
3, the cataclysm of the cataclysm should be zombi_host instead of zombi_origin.
4. With the increasing number of Cataclysm monsters, the FPS frame rate of the game will decrease and become more and more stuck. It is suggested that the author change to the boss version.
Plus: The characters in the second round of the biochemical model will be unified. Personal speculation is that there is a problem with Adding Role Plug-ins. You can try to delete or modify it.

**Comment by MoeMod** [comment]
1. Zombie Scenario is only for testing NPCs' AI. It doesn't include custom map supports, which needs further development. 
2. In v16 humans will get different amount of bpammo in different gameplay (coming soon). And then player can buy 600 bpammos.
3. If you want to test CSO maps, make sure you are using the original .bsp and .nav files, and mp.dll will try to parse them without fixing for CS16.
4. Due to the performance difference between PCs and phones, it is not recommanded to run Zombie Scenario in low-end phones.

**Comment by MoeMod** [comment]
fps in ZBS mode should be increased in v17.
the others is to be fixed.
moved to #42
