### ISSUE TITLE
Bot can't defuse the bomb

### ISSUE THREAD

**Issue by ghost** [MoeMod/CSMoE#34]
I'm playing original mode and seeing bots can't defuse the bomb, 

and I see a lot of immovable terrorists in cs_assault and other maps

i think you are really focusing on zombie mode so the original mode gets damaged

**Comment by MoeMod** [comment]
1. It can be fixed by providing the missing BotProfiles.db, which can be grabbed from czero. 
2. Up to now the nav reader cannot read the cs_assault.nav from steam cs. And the current nav builder doesn't provide with same performance than the steam cs does. Maybe merge the new nav codes from Regamedll will help.

**Comment by MoeMod** [comment]
fixed in v22-citrus
