### ISSUE TITLE
missing textures? s3tc problem? 

### ISSUE THREAD

**Issue by Askmewho** [MoeMod/CSMoE#70]
Hi everyone!!! I have several questions.
my platform is a rpi3

1) how is the folder tree setup? because I have ton of missing textures and I want to check than the game its detecting the data correctly.
2) there is a lot of tga files ... maybe it just than VC4 cant extract the textures??
3) how to buy weapons?? there is no button configuration for that!
4) thanks as always. it runs smooth .

**Comment by MoeMod** [comment]
1. there should be csmoe, cstrike and valve folders with maybe some binaries. You can get csmoe from https://github.com/MoeMod/CSMoE-GameDir and cstrike+valve from steam or other cs
2. some model needs external .tga textures located in csmoe/models/texture \
maybe the graphics doesnt support yet... I am testing with some common platforms so that might be ignored. I dont know how it runs in arm linux or maybe other systems.
3. ` buy ` command handles it. Try to bind it with ` bind b buy ` and then B key is available for it.
4. my pleasure.

**Comment by Askmewho** [comment]
Solved, my mistake.

https://youtu.be/Ncw1KMzNuys

Closed!
